SELECT IT.ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_TREE AS IT LEFT JOIN ITEM_INFO AS II
ON IT.ITEM_ID = II.ITEM_ID
WHERE IT.ITEM_ID NOT IN (SELECT PARENT_ITEM_ID FROM ITEM_TREE WHERE PARENT_ITEM_ID IS NOT NULL)
ORDER BY ITEM_ID DESC