SELECT TITLE, A.BOARD_ID, B.REPLY_ID, B.WRITER_ID, B.CONTENTS, DATE_FORMAT(B.CREATED_DATE, "%Y-%m-%d") as CREATED_DATE
FROM USED_GOODS_BOARD AS A JOIN USED_GOODS_REPLY AS B
WHERE 
    A.BOARD_ID = B.BOARD_ID AND
    A.CREATED_DATE LIKE "2022-10-%"
ORDER BY CREATED_DATE, TITLE