SELECT CONCAT('/home/grep/src/', UGB.BOARD_ID, '/', FILE_ID, FILE_NAME, FILE_EXT) AS FILE_PATH 
FROM USED_GOODS_BOARD AS UGB LEFT JOIN USED_GOODS_FILE AS UGF
ON UGB.BOARD_ID = UGF.BOARD_ID
WHERE VIEWS IN (SELECT MAX(VIEWS) AS VIEWS FROM USED_GOODS_BOARD)
ORDER BY FILE_ID DESC