SELECT BOOK_ID, AUTHOR_NAME, DATE_FORMAT(PUBLISHED_DATE,'%Y-%m-%d') as PUBLISHED_DATE
FROM (SELECT * FROM BOOK WHERE CATEGORY = '경제') AS B LEFT JOIN AUTHOR AS A
ON B.AUTHOR_ID = A.AUTHOR_ID
ORDER BY PUBLISHED_DATE